---

- name: Start ELK container.
  docker_container:
    name: cmaker-elk
    image: sebp/elk:{{ ELK_VERSION }}
    state: started
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    volumes:
      - "/srv/docker/elasticsearch:/etc/elasticsearch"
      - "/src/docker/logstash:/etc/logstash/"
